# Generated by Django 3.2.5 on 2021-07-29 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_intakedata_maindata_submitdata_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='accessDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Access Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='authCode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
