# Generated by Django 3.2.5 on 2021-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20210729_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userData',
            field=models.JSONField(default=list),
        ),
    ]
