import React from 'react';
import { createSlice, createAsyncThunk} from '@reduxjs/toolkit';
import { client_copy } from './client_copy'


// state holds everytab's copy of logic from "nocode" json exported from smartsheetdoc
const initialState = {
    entryStarted: false
}


export const homeSlice = createSlice({
    name: 'home',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        entryStarted: (state, action) => {
            state.entryStarted = true
        },
        entryCleared: (state, action) => {
            state.entryStarted = false
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: {
    }
  });

  export default homeSlice.reducer;
